declare module ASModule {
  type i8 = number;
  type i16 = number;
  type i32 = number;
  type i64 = BigInt;
  type isize = number;
  type u8 = number;
  type u16 = number;
  type u32 = number;
  type u64 = BigInt;
  type usize = number;
  type f32 = number;
  type f64 = number;
  type bool = any;
  export function __alloc(size: usize, id: u32): usize;
  export function __retain(ptr: usize): usize;
  export function __release(ptr: usize): void;
  export function __collect(): void;
  export var __rtti_base: usize;
  export function consoleLog(message: i32): void;
  export var BLOCK_STATE: usize;
  export var BOARD_STATE: usize;
  export function new_game(): void;
  export function block_drop(): bool;
  export function block_right(): bool;
  export function block_left(): bool;
  export function block_rotate_cw(): bool;
  export function block_rotate_ccw(): bool;
}
export default ASModule;
